leftnav:
- identifier: 5beee33e-d69d-b469-a4a7-b836781fa9c3
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: d56b6e87-3f28-82fa-dd55-252ba7fcdfa7
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: bb8941a8-2595-1725-8dd2-40d06532f3a0
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 30
- identifier: 04bf2dc2-6c58-0411-a974-352ddf413671
  name: Assignments
  url: /pages/assignments
  weight: 40
- identifier: 766f9880-d5c8-4376-4bd0-ed6a2d4d63ac
  name: Exams
  url: /pages/exams
  weight: 50
- identifier: 4db808ee-d3d7-16fe-f444-9174dad08a30
  name: Readings
  url: /pages/readings
  weight: 60
